/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class EsqueceuSenha extends javax.swing.JFrame {

  private String email,seg,senha;
    public EsqueceuSenha() {
        initComponents();
         setLocationRelativeTo(null); //CENTRALIZAR TELA
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoEsqueceuSen = new javax.swing.JButton();
        BotaoRegis = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();
        emailVeri = new javax.swing.JTextField();
        btnCon = new javax.swing.JButton();
        segCampo = new javax.swing.JTextField();
        novaSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoEsqueceuSen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Botao Esqueceu senha.png"))); // NOI18N
        BotaoEsqueceuSen.setBorder(null);
        getContentPane().add(BotaoEsqueceuSen, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 470, 120, 20));

        BotaoRegis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/botao link Registrar-se.png"))); // NOI18N
        BotaoRegis.setBorder(null);
        getContentPane().add(BotaoRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 90, 20));

        BotaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Captura de tela 2022-10-19 213715.png"))); // NOI18N
        BotaoSair.setBorder(null);
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 8, 30, 30));

        emailVeri.setBackground(new java.awt.Color(217, 217, 217));
        emailVeri.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        emailVeri.setBorder(null);
        emailVeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailVeriActionPerformed(evt);
            }
        });
        getContentPane().add(emailVeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 184, 280, 20));

        btnCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Botao Redefinir.png"))); // NOI18N
        btnCon.setBorder(null);
        btnCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConActionPerformed(evt);
            }
        });
        getContentPane().add(btnCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 385, 170, 50));

        segCampo.setBackground(new java.awt.Color(217, 217, 217));
        segCampo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        segCampo.setBorder(null);
        segCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segCampoActionPerformed(evt);
            }
        });
        getContentPane().add(segCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 248, 280, 20));

        novaSenha.setBackground(new java.awt.Color(217, 217, 217));
        novaSenha.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        novaSenha.setBorder(null);
        getContentPane().add(novaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 317, 280, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/RedefinirSenha Tela.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailVeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailVeriActionPerformed
        
    }//GEN-LAST:event_emailVeriActionPerformed

    private void btnConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConActionPerformed
        email = emailVeri.getText();
        seg = segCampo.getText();
        senha = novaSenha.getText();
        if(email.equals("")){
                 JOptionPane.showMessageDialog(null,"Email em branco!!!","Erro",JOptionPane.ERROR_MESSAGE);
                } 
     
     else{
        
        try {
            String email,seg;

            email = emailVeri.getText();
            seg = segCampo.getText();
            
            UsuarioDTO objseg = new UsuarioDTO();
            objseg.setEmail(email);
            objseg.setSeg(seg);

            UsuarioDAO objDAO = new UsuarioDAO();
            ResultSet rsusuariodao = objDAO.VerificacaoSeguranca(objseg);
            if(rsusuariodao.next())
            {
              senha = novaSenha.getText();
              UsuarioDTO objsenha = new UsuarioDTO();
              objsenha.setSenha(senha);
              UsuarioDAO objSenha2 = new UsuarioDAO();
              objSenha2.alterarSenha(objsenha);
              JOptionPane.showMessageDialog(null,"Senha trocada com sucesso!!!","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
            JOptionPane.showMessageDialog(null,"Senha inválida!!!","Erro",JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "btnlogin");
        }
        }
    }//GEN-LAST:event_btnConActionPerformed

    private void segCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segCampoActionPerformed

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoSairActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoEsqueceuSen;
    private javax.swing.JButton BotaoRegis;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JButton btnCon;
    private javax.swing.JTextField emailVeri;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField novaSenha;
    private javax.swing.JTextField segCampo;
    // End of variables declaration//GEN-END:variables
}
