/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.ConexaoDAO;
import DTO.UsuarioDTO;
import UTIL.ManipularImagem;
import java.awt.Frame;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import view.PagamentoRealizado.RandomString;

/**
 *
 * @author Cliente
 */
public class PagamentoRealizado extends javax.swing.JFrame {

    public PagamentoRealizado() {
        initComponents();
        setLocationRelativeTo(null); //CENTRALIZAR TELA
        RandomString obj = new RandomString();
        String codigo = campoCodigo.getText();
        String jogo = null;
        String email = null;
        
        java.sql.Connection conn = new ConexaoDAO().conectaBD();
        try {
            String sql = "Select (email) from user where status = ?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setInt(1,1);
            ResultSet rs = pstm.executeQuery();
            while(rs.next()){
            email = rs.getString(1);
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,erro + "campoPreço");
            }
            try {
            String sql = "Select (nome) from jogos where status = ?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setInt(1,1);
            ResultSet rs = pstm.executeQuery();
            while(rs.next()){
            jogo = rs.getString(1);
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,erro + "campoPreço");
            }    
        try {
                 String sql1 = "INSERT into vendas (email,jogo,codigo,status) values(?,?,?,1)";
                 PreparedStatement pstm1 = conn.prepareStatement(sql1);
                 pstm1.setString(1,email);
                 pstm1.setString(2,jogo);
                 pstm1.setString(3,codigo);
                 pstm1.execute();
                
                 
            } catch (SQLException erro) {
                JOptionPane.showMessageDialog(null,erro + "Insert");
            }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoInicio = new javax.swing.JButton();
        BotaoFechar = new javax.swing.JButton();
        campoCodigo = new javax.swing.JTextField();
        btnCopiar = new javax.swing.JButton();
        ImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Botao Inicio Branco.png"))); // NOI18N
        BotaoInicio.setBorder(null);
        BotaoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, -1, -1));

        BotaoFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Captura de tela 2022-10-19 213715.png"))); // NOI18N
        BotaoFechar.setBorder(null);
        BotaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFecharActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 30, 30));

        campoCodigo.setEditable(false);
        getContentPane().add(campoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 180, -1));

        btnCopiar.setText("copiar");
        btnCopiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCopiarMousePressed(evt);
            }
        });
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCopiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, -1, -1));

        ImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Tela Pagamento Concluido.png"))); // NOI18N
        getContentPane().add(ImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoInicioActionPerformed
     
     TelaPrincLog obj = new TelaPrincLog();
     obj.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_BotaoInicioActionPerformed

    private void BotaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFecharActionPerformed
        UsuarioDTO objseg = new UsuarioDTO();
        DAO.UsuarioDAO objDAO = new DAO.UsuarioDAO();
        ResultSet rsusuariodao = objDAO.Deconnect(objseg);
        System.exit(0);
    }//GEN-LAST:event_BotaoFecharActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        Clipboard clipBoard = getToolkit().getSystemClipboard();
        StringSelection ss = new StringSelection(campoCodigo.getText());
        clipBoard.setContents(ss,ss);
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnCopiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCopiarMousePressed
        JOptionPane.showMessageDialog(null,"Código copiado com sucesso!!!");
        UsuarioDTO objseg = new UsuarioDTO();
        DAO.UsuarioDAO objDAO = new DAO.UsuarioDAO();
        ResultSet rsusuariodao = objDAO.Cancelamento(objseg);
        TelaPrincLog obj = new TelaPrincLog();
        obj.setVisible(true);
        
    }//GEN-LAST:event_btnCopiarMousePressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFechar;
    private javax.swing.JButton BotaoInicio;
    private javax.swing.JLabel ImagemFundo;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JTextField campoCodigo;
    // End of variables declaration//GEN-END:variables
     public class RandomString {
    static String getAlphaNumericString(int n)
    {
        String AlphaNumericString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" + "0123456789";
        StringBuilder sb = new StringBuilder(n);
        for (int i = 0; i < n; i++) {
            int index
                = (int)(AlphaNumericString.length()
                        * Math.random());
            sb.append(AlphaNumericString
                          .charAt(index));
        }
        return sb.toString();
    }
    
    {
        int n = 12;
        campoCodigo.setText(""+RandomString.getAlphaNumericString(n));
    }
}
}
