/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Frame;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import view.PagamentoRealizado.RandomString;

/**
 *
 * @author Cliente
 */
public class PagamentoRealizado extends javax.swing.JFrame {

    public PagamentoRealizado() {
        initComponents();
        setLocationRelativeTo(null); //CENTRALIZAR TELA
        btnCopiar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoInicio = new javax.swing.JButton();
        BotaoFechar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        campoCodigo = new javax.swing.JTextField();
        btnCopiar = new javax.swing.JButton();
        ImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Botao Inicio Branco.png"))); // NOI18N
        BotaoInicio.setBorder(null);
        BotaoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, -1, -1));

        BotaoFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Captura de tela 2022-10-19 213715.png"))); // NOI18N
        BotaoFechar.setBorder(null);
        BotaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFecharActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 30, 30));

        jButton1.setText("Revelar código");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, -1, -1));

        campoCodigo.setEditable(false);
        getContentPane().add(campoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, 180, -1));

        btnCopiar.setText("copiar");
        btnCopiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCopiarMousePressed(evt);
            }
        });
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCopiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 570, -1, -1));

        ImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Tela Pagamento Concluido.png"))); // NOI18N
        getContentPane().add(ImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoInicioActionPerformed
     TelaPrincLog obj = new TelaPrincLog();
     obj.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_BotaoInicioActionPerformed

    private void BotaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFecharActionPerformed
      System.exit(0);
    }//GEN-LAST:event_BotaoFecharActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        RandomString obj = new RandomString();
        btnCopiar.setVisible(true);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        Clipboard clipBoard = getToolkit().getSystemClipboard();
        StringSelection ss = new StringSelection(campoCodigo.getText());
        clipBoard.setContents(ss,ss);
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnCopiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCopiarMousePressed
        JOptionPane.showMessageDialog(null,"Código copiado com sucesso!!!");
    }//GEN-LAST:event_btnCopiarMousePressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFechar;
    private javax.swing.JButton BotaoInicio;
    private javax.swing.JLabel ImagemFundo;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
     public class RandomString {
  
   
    static String getAlphaNumericString(int n)
    {
        String AlphaNumericString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" + "0123456789";
        StringBuilder sb = new StringBuilder(n);
        for (int i = 0; i < n; i++) {
            int index
                = (int)(AlphaNumericString.length()
                        * Math.random());
            sb.append(AlphaNumericString
                          .charAt(index));
        }
        return sb.toString();
    }
    
    {
        int n = 12;
        campoCodigo.setText(""+RandomString.getAlphaNumericString(n));
    }
}
      public void copy (){
        
 }
 
}
