/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.ConexaoDAO;
import DTO.UsuarioDTO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author luisr
 */
public class TelaPIX extends javax.swing.JFrame {

    /**
     * Creates new form TelaPIX
     */
    public TelaPIX() {
        initComponents();
        java.sql.Connection conn = new ConexaoDAO().conectaBD();
        setLocationRelativeTo(null); //CENTRALIZAR TELA
        int x = 0;
        int y = 0;
        int z = 0;
        int soma = 0;
         try {
            String sql = "Select valor from jogos where status = ?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setInt(1,1);
            ResultSet rs = pstm.executeQuery();
            while(rs.next()){
            x = rs.getInt(1);
            }
            campoValor.setText("R$"+x);
            y = x / 10;
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,erro + "campoPreço");
            }
         try {
            String sql = "Select moedas from user where status = ?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setInt(1,1);
            ResultSet rs = pstm.executeQuery();
            while(rs.next()){
            z = rs.getInt(1);
            }
            soma = z+y;
          
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,erro + "Moedas");
            }
         try {
            String sql = "Update user set moedas = ? where status = ?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setInt(1,soma);
            pstm.setInt(2,1);
            pstm.execute();
       
            
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,erro + "Moedas");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoVoltar = new javax.swing.JButton();
        campoValor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        BotaoFechar = new javax.swing.JButton();
        campoDesconto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BotaoVoltar.png"))); // NOI18N
        BotaoVoltar.setBorder(null);
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        campoValor.setEditable(false);
        campoValor.setBackground(new java.awt.Color(255, 255, 255));
        campoValor.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        campoValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoValor.setBorder(null);
        campoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorActionPerformed(evt);
            }
        });
        getContentPane().add(campoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 360, 160));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/botaoPagamentoEfetuado.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 565, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(82, 113, 255));
        jTextField2.setForeground(new java.awt.Color(82, 113, 255));
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, 50));

        BotaoFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Captura de tela 2022-10-19 213715.png"))); // NOI18N
        BotaoFechar.setBorder(null);
        BotaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFecharActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 5, 20, 20));

        campoDesconto.setEditable(false);
        campoDesconto.setBackground(new java.awt.Color(255, 255, 255));
        campoDesconto.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        campoDesconto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoDesconto.setBorder(null);
        campoDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescontoActionPerformed(evt);
            }
        });
        getContentPane().add(campoDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 360, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Tela Pix.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorActionPerformed
      
    }//GEN-LAST:event_campoValorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       PagamentoRealizado obj = new PagamentoRealizado();
       obj.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFecharActionPerformed
        UsuarioDTO objseg = new UsuarioDTO();
        DAO.UsuarioDAO objDAO = new DAO.UsuarioDAO();
        ResultSet rsusuariodao = objDAO.Deconnect(objseg);
        System.exit(0);
    }//GEN-LAST:event_BotaoFecharActionPerformed

    private void campoDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDescontoActionPerformed

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        
        UsuarioDTO objseg = new UsuarioDTO();
        DAO.UsuarioDAO objDAO = new DAO.UsuarioDAO();
        ResultSet rsusuariodao = objDAO.Cancelamento(objseg);
        TelaPrincLog obj = new TelaPrincLog();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFechar;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JTextField campoDesconto;
    private javax.swing.JTextField campoValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
